#!/bin/bash

# norms 0.1, 0.2, 0.5, 1, 2, 5, 10, 20, 50, 100, 200, 500, 1000
# num_views 720, 360, 180, 90, 45, 22, 11, 6

script_args=(
    "--nonnegative --num_epochs 0 --norm 0.1 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 0.1 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 0.1 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 0.1 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 0.1 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 0.1 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 0.1 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 0.1 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 0.2 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 0.2 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 0.2 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 0.2 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 0.2 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 0.2 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 0.2 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 0.2 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 0.5 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 0.5 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 0.5 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 0.5 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 0.5 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 0.5 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 0.5 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 0.5 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 1 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 1 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 1 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 1 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 1 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 1 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 1 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 1 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 2 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 2 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 2 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 2 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 2 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 2 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 2 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 2 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 5 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 5 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 5 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 5 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 5 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 5 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 5 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 5 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 10 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 10 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 10 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 10 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 10 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 10 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 10 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 10 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 20 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 20 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 20 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 20 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 20 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 20 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 20 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 20 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 50 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 50 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 50 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 50 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 50 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 50 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 50 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 50 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 100 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 100 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 100 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 100 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 100 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 100 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 100 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 100 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 200 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 200 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 200 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 200 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 200 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 200 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 200 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 200 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 500 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 500 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 500 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 500 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 500 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 500 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 500 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 500 --num_views 720"
    "--nonnegative --num_epochs 0 --norm 1000 --num_views 6"
    "--nonnegative --num_epochs 0 --norm 1000 --num_views 11"
    "--nonnegative --num_epochs 0 --norm 1000 --num_views 22"
    "--nonnegative --num_epochs 0 --norm 1000 --num_views 45"
    "--nonnegative --num_epochs 0 --norm 1000 --num_views 90"
    "--nonnegative --num_epochs 0 --norm 1000 --num_views 180"
    "--nonnegative --num_epochs 0 --norm 1000 --num_views 360"
    "--nonnegative --num_epochs 0 --norm 1000 --num_views 720"
)

# Loop through each set of arguments
for i in "${!script_args[@]}"; do
    script="p4_copy2.py"
    args=(${script_args[$i]})  # Split the string into an array
    echo "Running $script with arguments: ${args[@]}"
    python "$script" "${args[@]}"  # Pass the array as separate arguments
    # Check if the previous command was successful
    if [ $? -ne 0 ]; then
        echo "Error: $script failed."
        exit 1
    fi
done
